name: 'SEO'
description: 'Sets up modules and configurations for SEO'
type: 'Site'

install:
  - metatag
  - metatag:metatag_open_graph
  - metatag:metatag_twitter_cards
  - pathauto
  - redirect
  - robotstxt
  - schema_metatag
  - schema_metatag:schema_web_site
  - schema_metatag:schema_web_page
  - simple_sitemap

config:
  import:
    metatag: '*'
    redirect:
      - system.action.redirect_delete_action
      - views.view.redirect
    pathauto:
      - pathauto.pattern.content
      - pathauto.pattern.taxonomy_term
      - pathauto.pattern.user
    simple_sitemap:
      - simple_sitemap.custom_links.default
      - simple_sitemap.sitemap.content
      - simple_sitemap.sitemap.index
      - simple_sitemap.type.content
      - simple_sitemap.type.index
