name: 'SEO'
description: 'Sets up modules and configurations for SEO'
type: 'Site'

install:
  - metatag
  - metatag:metatag_open_graph
  - metatag:metatag_twitter_cards
  - pathauto
  - redirect
  - robotstxt
  - schema_metatag
  - schema_metatag:schema_web_site
  - schema_metatag:schema_web_page

config:
  import:
    metatag:
      - metatag.metatag_defaults.403
      - metatag.metatag_defaults.404
      - metatag.metatag_defaults.front
      - metatag.metatag_defaults.global
      - metatag.metatag_defaults.node
      - metatag.metatag_defaults.taxonomy_term
      - metatag.metatag_defaults.user
      - metatag.settings
    redirect:
      - redirect.settings
    pathauto:
      - pathauto.settings
      - pathauto.pattern.content
      - pathauto.pattern.taxonomy_term
      - pathauto.pattern.user
